-- SMART TAHFIDZ: additive schema. Jalankan manual di Supabase SQL Editor.
create extension if not exists pgcrypto;
alter table if exists public.tahfidz_quran add column if not exists juz smallint;
alter table if exists public.tahfidz_quran add column if not exists created_at timestamptz default now();
alter table if exists public.tahfidz_quran add column if not exists updated_at timestamptz default now();
alter table if exists public.tilawah_harian add column if not exists juz smallint;
alter table if exists public.tilawah_harian add column if not exists created_at timestamptz default now();
alter table if exists public.tilawah_harian add column if not exists updated_at timestamptz default now();
alter table if exists public.tahsin_quran add column if not exists jilid smallint;
alter table if exists public.tahsin_quran add column if not exists halaman integer;
alter table if exists public.tahsin_quran add column if not exists created_at timestamptz default now();
alter table if exists public.tahsin_quran add column if not exists updated_at timestamptz default now();
create table if not exists public.quran_juz (nomor smallint primary key check (nomor between 1 and 30), nama text not null, created_at timestamptz not null default now());
create table if not exists public.quran_surat (nomor smallint primary key check (nomor between 1 and 114), nama text not null unique, urutan smallint not null, created_at timestamptz not null default now());
create table if not exists public.quran_juz_surat (juz smallint not null references public.quran_juz(nomor) on delete cascade, surat smallint not null references public.quran_surat(nomor) on delete cascade, primary key (juz,surat));
create index if not exists tahfidz_quran_juz_idx on public.tahfidz_quran(juz);
create index if not exists quran_juz_surat_surat_idx on public.quran_juz_surat(surat);
create index if not exists tahfidz_quran_student_date_idx on public.tahfidz_quran(siswa_id,tanggal desc);
create index if not exists tilawah_student_date_idx on public.tilawah_harian(siswa_id,tanggal desc);
create index if not exists tahsin_student_date_idx on public.tahsin_quran(siswa_id,tanggal desc);
create index if not exists tahsin_jilid_halaman_idx on public.tahsin_quran(jilid,halaman);
alter table public.quran_juz enable row level security;
alter table public.quran_surat enable row level security;
alter table public.quran_juz_surat enable row level security;
drop policy if exists "quran master readable" on public.quran_juz;
drop policy if exists "quran surah readable" on public.quran_surat;
drop policy if exists "quran map readable" on public.quran_juz_surat;
create policy "quran master readable" on public.quran_juz for select to authenticated using (true);
create policy "quran surah readable" on public.quran_surat for select to authenticated using (true);
create policy "quran map readable" on public.quran_juz_surat for select to authenticated using (true);
alter table if exists public.tahsin_quran enable row level security;
drop policy if exists "parent reads own child tahsin" on public.tahsin_quran;
create policy "parent reads own child tahsin" on public.tahsin_quran for select to authenticated using (exists (select 1 from public.orang_tua_siswa r where r.user_id=auth.uid() and r.siswa_id=tahsin_quran.siswa_id));
comment on table public.quran_juz is 'Master 30 juz untuk cascading selection dan verifikasi penyelesaian.';
comment on table public.quran_surat is 'Master 114 surat; jangan mengulang daftar surat di tiap halaman.';
